name: job1

permissions:
  checks: write
  contents: write
  pull-requests: write

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1 Step
        run: echo "Job1 was successful"
