name: job2

permissions:
  checks: write
  contents: write
  pull-requests: write

on:
  pull_request:

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job2 Step
        run: echo "Job2 was successful"
