name: notify-mod
run-name: Notify about a Pull Request if all checks are passed (modded)

on:
  workflow_run:
    workflows: ["job1", "job2"]
    types:
      - completed

jobs:
  notify:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.name == 'job1'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Wait for other workflow
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-job1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: job1
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Wait for other workflow
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-job2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: job2
          ref: ${{ github.event.workflow_run.head_commit.id }}

      - name: Notify
        if: steps.wait-for-job1.outputs.conclusion == 'success' && steps.wait-for-job2.outputs.conclusion == 'success'
        run: echo "Both job1 and job2 were successful."
