name: notify-mod-3
run-name: Notify about a Pull Request if all checks are passed (modded-3)

on:
  pull_request:

jobs:
  wait-for-workflows:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    outputs:
      job1-result: ${{ steps.wait-for-job1.outputs.conclusion }}
      job2-result: ${{ steps.wait-for-job2.outputs.conclusion }}
    steps:
      - name: Wait for job1 workflow
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-job1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: job1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Wait for job2 workflow
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-job2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: job2
          ref: ${{ github.event.pull_request.head.sha }}

  notify-slack:
    if: >
      needs.wait-for-status.outputs.job1-success == 'success'
      && needs.wait-for-status.outputs.job2-success == 'success'
    needs: [wait-for-workflows]
    runs-on: ubuntu-latest
    steps:
      - name: Post payload to Slack Webhook
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK_URL }}
        with:
          payload: |
            {
              "url": ${{ toJson(github.event.pull_request.html_url) }},
              "title": ${{ toJson(github.event.pull_request.title) }},
              "description": ${{ toJson(github.event.pull_request.body) }},
              "user": ${{ toJson(github.event.sender.login) }}
            }
