name: notify-mod
run-name: Notify about a Pull Request if all checks are passed (modded)

on:
  workflow_run:
    workflows: ["job1", "job2"]
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    outputs:
      job1-success: ${{ steps.check-job1.outputs.success }}
      job2-success: ${{ steps.check-job2.outputs.success }}
    steps:
      - name: Check job1 success
        id: check-job1
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const workflowRuns = await github.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'completed',
              branch: '${{ github.event.workflow_run.head_branch }}'
            });
            const job1Run = workflowRuns.data.workflow_runs.find(run => run.name === 'job1' && run.conclusion === 'success');
            core.setOutput('success', job1Run ? 'true' : 'false');

      - name: Check job2 success
        id: check-job2
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const workflowRuns = await github.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: 'completed',
              branch: '${{ github.event.workflow_run.head_branch }}'
            });
            const job2Run = workflowRuns.data.workflow_runs.find(run => run.name === 'job2' && run.conclusion === 'success');
            core.setOutput('success', job2Run ? 'true' : 'false');
  notify:
    needs: [check-status]
    if: ${{ needs.check-status.outputs.job1-success == 'true' && needs.check-status.outputs.job2-success == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Final Step
        run: echo "All previous jobs were successful"
