name: notify
run-name: Notify about a Pull Request if all checks are passed

on:
  workflow_run:
    workflows: [ "job1" ]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Final Step
        run: echo "All previous jobs were successful"
