name: notify-mod-2
run-name: Notify about a Pull Request if all checks are passed (modded)

on:
  pull_request:

jobs:
  notify:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other workflow
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-job1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: job1
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for other workflow
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-job2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: job2
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Post message to Slack Webhook
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK_URL }}
        with:
          payload: |
            {
              "url": ${{ toJson(github.event.pull_request.html_url) }},
              "title": ${{ toJson(github.event.pull_request.title) }},
              "description": ${{ toJson(github.event.pull_request.body) }},
              "user": ${{ toJson(github.event.sender.login) }}
            }
