name: notify
run-name: Notify about a Pull Request if all checks are passed

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - name: Final Step
        run: echo "All previous jobs were successful"
